name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels: ['feat', 'feature']
  - title: 'Fixes'
    labels: ['fix', 'bugfix', 'bug']
  - title: 'Docs'
    labels: ['docs']
  - title: 'Chore'
    labels: ['chore']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

